apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: akiutoslahti-calculus-demo-node
  labels:
    app: akiutoslahti-calculus-demo-node

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: akiutoslahti-calculus-demo-node

  template:
    metadata:
      labels:
        app: akiutoslahti-calculus-demo-node
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/akiutoslahti-calculus-demo-node:latest
          name: akiutoslahti-calculus-demo-node
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        service: workshop
