apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: aki-calculus
  labels:
    app: aki-calculus

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: aki-calculus

  template:
    metadata:
      labels:
        app: aki-calculus
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/aki-calculus:latest
          name: aki-calculus
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: SOME_ENV_VARIABLE
              value: some env value

      nodeSelector:
        service: workshop
