kind: Service
apiVersion: v1
metadata:
  labels:
    app: akiutoslahti-calculus-demo-node
  name: akiutoslahti-calculus-demo-node
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: akiutoslahti-calculus-demo-node
